<?php
$translate=array(
"Acces evaluari" => "доступ оценки",
"Acces feedback" => "Доступ Обратная связь",
"Adauga companie" => "Добавить компанию",
"Admin" => "админ",
"Anunturi" => "Объявления",
"Biblioteca" => "Библиотека",
"Cauta" => "Поиск",
"Cereri" => "Запросы",
"Companii" => "Компании",
"Contacte" => "Контакты",
"Export" => "Экспорт",
"Home" => "Главная",
"Joburi" => "Вакансии",
"Limba" => "Язык",
"Nume" => "Фамилия",
"Orase" => "Город",
"Personal" => "Сотрудники",
"Pontaj" => "Табель",
"Prenume" => "Имя",
"Printeaza pagina" => "Печать страницы",
"Printeaza tot" => "Печать",
"Proiecte" => "Проекты",
"Setari" => "Настройки",
"Status" => "Статус",
"Stiri" => "Новости",
"Training" => "Тренинги",
"Varsta" => "Возраст",
);
?>