descriptions = new Array("Adauga persoana Top Previous Next Pentru a putea vizualiza persoanele adaugate in aplicatia HR Suite: • se alege din meniul principal [Personal] •...",
	"Utilizator Top Previous Next Pentru adaugarea unui utilizator nou se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul...",
	"Adauga companie Top Previous Next Pentru a putea vizualiza comaniile adaugate in aplicatia HR Suite: • se alege din meniul principal [Companii] • ...",
	"Adauga eveniment Top Previous Next Pentru a putea vizualiza evenimentele adaugate in aplicatia HR Suite: • se alege din meniul principal optiunea ...",
	"Adauga job Top Previous Next Pentru a putea vizualiza joburile adaugate in aplicatia HR Suite: • se alege din meniul principal [Joburi] • din subm...",
	"Profesie Top Previous Next Pentru adaugarea unei noi profesii se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Ad...",
	"Adauga training Top Previous Next Pentru a putea adauga Traininguri in aplicatia HR Suite: • se alege din meniul principal optiunea [Training] • d...",
	"Administrare Top Previous Next Modulul [Administrare] al aplicatiei HR Suite se foloseste pentru a accesa informatiile necesare unei functionari c...",
	"Aplicatii Top Previous Next Aplicatia HR Suite permite configurarea mai multor aplicatii. O aplicatie poate fi un program informatic al companiei ...",
	"Aplicatii Top Previous Next Pentru adaugarea unei noi aplicatii se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [...",
	"Autentificarea Top Previous Next Prima fereastra pe care o vede un utilizator care doreste sa foloseasca aplicatia HR Suite este fereastra de aute...",
	"Campuri custom Top Previous Next Aplicatia informatica HR Suite permite, pe langa informatiile generale, si introducerea unor informatii configura...",
	"Centre de cost Top Previous Next Aplicatia HR Suite permite configurarea centrelor de cost ale companiei dumneavoastra. ",
	"Centre de cost Top Previous Next Pentru adaugarea unui nou centru de cost se urmeaza pasii: • din meniul principal se alege [Administrare] • din s...",
	"Companii Top Previous Next Pentru a putea vizualiza companiile adaugate in aplicatia HR Suite, se alege din meniul principal optiunea [Companii]. ...",
	"Companii Top Previous Next Modulul de gestionare a companiilor care colaboreaza sau au colaborat, sau au fost inregistrate de catre personalul com...",
	"Companii training Top Previous Next Pentru a putea vizualiza o lista a companiilor de training adaugate in aplicatia HR Suite, se alege din meniul...",
	"Fereastra CV Top Previous Next Campurile introduse anterior necesare pentru completarea unui CV sunt preluate automat. Aceste campuri sunt: Nume s...",
	"Departamente Top Previous Next Aplicatia HR Suite permite configurarea departamentelor existente in cadrul companiei dumneavoastra, dar nu numai. ",
	"Departament Top Previous Next Pentru adaugarea unui nou departament se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeni...",
	"Despre HR Suite 1.0 Top Previous HR Suite Version 1.0 Informatii despre numerotarea versiuniilor aplicatiei HR Suite Aplicatia HR Suite are doua t...",
	"Domenii Top Previous Next Aplicatia HR Suite permite configurarea de domeniilor de activitate pe care compania dumneavoastra le intalneste sau le ...",
	"Domenii Top Previous Next Pentru adaugarea unui nou domeniu se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Admi...",
	"Evenimente Top Previous Next Fereastra evenimente contine lista completa a evenimentelor introduse in aplicatie. Prin evenimente se poate intelege...",
	"Fereastra Concediu Top Previous Next Ferastra [Concediu de odihna] contine urmatoarele campuri: Concediu de odihna (setare numar de zile de conced...",
	"Fereastra Date profesionale Top Previous Next Fereastra [Date profesionale] • Profesia: (camp obligatoriu de completat) • Pregatire:(camp obligato...",
	"Fereastra Masini Top Previous Next In aceastra fereastra se poate specifica daca persoana are masina primita de la companie. Se mai pot competa si...",
	"Fereastra Payroll Top Previous Next Ferastra [Payroll] contine urmatoarele campuri: • Data angajarii: (camp obligatoriu) - data la care persoana a...",
	"Functie Top Previous Next Pentru adaugarea unei noi functii se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Admi...",
	"Functii Top Previous Next Aplicatia HR Suite permite configurarea tuturor functiilor pe care compania dumneavoastra le foloseste. ",
	"Help Top Previous Next Help Pentru a putea gasi informatia dorita despre functionalitatile aplicateiei HR Suite se pot folosi urmatoarele: Index s...",
	"Home Top Previous Next Pagina 'Home' (sau Pagina de start) contine stiri si informatii de profil, utile pentru persoanele care folosesc aplicatia ...",
	"Informatii generale Top Previous Next Pentru a putea vedea oricand cine este autentificat, aplicatia HR Suite va afiseaza in partea stanga, in col...",
	"Introducere Top Next HR Suite este o aplicatie informatica care are ca scop usurarea gestionarii activitatilor dintr-un departament de Resurse Uma...",
	"Joburi Top Previous Next Pentru a putea vizualiza joburile adaugate in aplicatia HR Suite, se alege din meniul principal optiunea [Joburi]. Aplica...",
	"Joburi Top Previous Next Modulul de gestionare a joburilor. Aici se pot vedea joburile vacante in cadrul companiei sau chiar joburi vacante identi...",
	"Lista evenimente Top Previous Next Pentru a putea vizualiza evenimentele adaugate in aplicatia HR Suite, se alege din meniul principal optiunea [E...",
	"Lista personalizata Top Previous Next Acest modul se poate folosi pentru a adauga coloane aditionale in listele Personal, Companii si Joburi. Pent...",
	"Lista traininguri Top Previous Next Pentru a putea vizualiza trainingurile adaugate in aplicatia HR Suite, se alege din meniul principal optiunea ...",
	"Locatie Top Previous Next Pentru adaugarea unei noi locatii se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Admi...",
	"Locatii si sali Top Previous Next Aplicatia HR Suite permite configurarea mai multor locatii si sali. O locatie poate fi sediul central al compani...",
	"Module Top Previous Next Pentru adaugarea unui nou modul se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Adminis...",
	"Fereastra Modul IT Top Previous Next Ferastra [Modul IT], folosita pentru a specifica drepturile in aplicatiile companiei pentru fiecare angajat, ...",
	"Personal Top Previous Next Meniul [Personal] este folosit pentru a putea vedea lista completa a angajatilor actuali sau angajati care au parasit c...",
	"Personal Top Previous Next Pentru a putea vizualiza personele adaugate in aplicatia HR Suite, se alege din meniul principal [Personal], urmand ca ...",
	"Profesii Top Previous Next Aplicatia HR Suite permite configurarea profesiilor pe care compania dumneavoastra le intalneste, sau le foloseste, cel...",
	"Rapoarte Top Previous Next Aplicatia informatica HR Suite poate genera diferite tipuri de rapoarte. Pentru a putea acesa/rula rapoartele se folose...",
	"Rapoarte Top Previous Next Pentru setarea unui nou raport managerial se urmeaza pasii: • din meniul principal se alege [Administrare] • din submen...",
	"Sali Top Previous Next Pentru adaugarea unei noi sali se urmeaza pasii: • din meniul principal se apasa [Administrare] • din submeniul [Administra...",
	"Schimbarea parolei Top Previous Next Daca un utilizator doreste sa isi schimbe parola setata de administratorul aplicatiei, trebuie sa urmeze urma...",
	"Setare drepturi Top Previous Next Pentru setarea drepturilor de acces ale unui utilizator nou se urmeaza pasii: • din meniul principal se apasa [A...",
	"Setare parola Top Previous Next Pentru a putea seta o noua parola pentru un utilizator se urmeaza pasii: • din meniul principal se alege [Administ...",
	"Setari Top Previous Next Afisarea listei personalizate, pe trei mari categorii – Personal, Companii, Joburi. Bifeaza si salveaza ceea ce te avanta...",
	"Setari speciale Top Previous Next Pentru setarea drepturilor speciale ale unui utilizator se urmeaza pasii: • din meniul principal se alege [Admin...",
	"Stergere utilizator Top Previous Next Pentru a sterge un utilizator se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeni...",
	"Tipuri de training Top Previous Next Pentru adaugarea unui nou tip de training se urmeaza pasii: • din meniul principal se alege [Training] • din ...",
	"Training Top Previous Next Meniul Training centralizeaza informatii despre traingurile desfasurate, planificate, sau programate si le grupeaza in ...",
	"Utilizatori Top Previous Next Pentru a putea folosi aplicatia HR Suite fiecare utilizator are nevoie de un utilizator si o parola. Administratorul...",
	"Bine ati venit Top Previous Next Aplicatia informatica, HR Suite, pentru gestionarea activitatilor dintr-un departament de resurse umane a fost ga...");