pageinfo = [[1233076705,6267],
	[1233080889,15652],
	[1233396529,6721],
	[1232998107,18219],
	[1232999113,8631],
	[1232998419,8869],
	[1233397355,4272],
	[1232999627,8380],
	[1233396461,1958],
	[1233397739,3708],
	[1233397789,4080],
	[1233399431,3053],
	[1233399323,2509],
	[1233076685,2532],
	[1233076617,3754],
	[1233076699,8540],
	[1218954741,1875],
	[1233397657,4472],
	[1232997693,10176],
	[1218905669,1897],
	[1232999233,10200],
	[1232997385,9939],
	[1232997565,2974],
	[1218955097,1897],
	[1233397715,4407],
	[1221665561,3223],
	[1233077179,3250],
	[1221664943,1897],
	[1233397487,4374],
	[1221663191,3240],
	[1232997595,3012],
	[1232997107,4937],
	[1226000095,8203],
	[1232996929,7336],
	[1232997535,5376],
	[1232997035,9701],
	[1233397409,4294],
	[1218953969,1862],
	[1218956227,1902],
	[1232999559,1977],
	[1232996313,2842],
	[1233215175,1900],
	[1233076719,5914],
	[1232998231,11462],
	[1219267059,1952],
	[1233076731,9670],
	[1232998941,11387],
	[1233081289,11515],
	[1232999491,21801],
	[1232999173,12552],
	[1233396909,4053],
	[1233396797,3819],
	[1233076713,6997],
	[1233397855,4833],
	[1232997475,4664],
	[1233081223,2845],
	[1233081299,5401],
	[1232996163,1929],
	[1232996449,2271],
	[1232996609,13633],
	[1218952641,1895],
	[1218905921,1910],
	[1221665187,3309],
	[1233397281,4754],
	[1233399395,8058],
	[1233396689,3868],
	[1233396571,4796],
	[1219269945,1890],
	[1233396713,5579],
	[1233396763,4951],
	[1232999307,4090],
	[1221663363,3805],
	[1233396497,3711],
	[1257255903,3817]];
pagedata = [ ["./actiune_noua.htm","Actiune noua","﻿Actiune noua Top Previous Next Modul Performanta &#62; Plan actiuni Fereastra [Actiune noua] contine urmatoarele elemente: Campurile: • Anul - anul p...",""],
["./adaugapersoana.htm","Adauga persoana","﻿Adauga persoana Top Previous Next Pentru a putea vizualiza persoanele adaugate in aplicatia HR Executive: • se alege din meniul principal [Person...",""],
["./adaugare_utilizator.htm","Utilizator","﻿Utilizator Top Previous Next Pentru adaugarea unui utilizator nou se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniu...",""],
["./adauga_companie.htm","Adauga companie","﻿Adauga companie Top Previous Next Pentru a putea vizualiza comaniile adaugate in aplicatia HR Executive: • se alege din meniul principal [Compani...",""],
["./adauga_eveniment.htm","Adauga eveniment","﻿Adauga eveniment Top Previous Next Pentru a putea vizualiza evenimentele adaugate in aplicatia HR Executive: • se alege din meniul principal opti...",""],
["./adauga_job.htm","Adauga job","﻿Adauga job Top Previous Next Pentru a putea vizualiza joburile adaugate in aplicatia HR Executive: • se alege din meniul principal [Joburi] • din...",""],
["./adauga_profesie.htm","Profesie","﻿Profesie Top Previous Next Pentru adaugarea unei noi profesii se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [A...",""],
["./adauga_training.htm","Adauga training","﻿Adauga training Top Previous Next Pentru a putea adauga Traininguri in aplicatia HR Executive: • se alege din meniul principal optiunea [Training...",""],
["./administrare.htm","Administrare","﻿Administrare Top Previous Next Fereastra [Administrare] al aplicatiei HR Executive se foloseste pentru a accesa informatiile necesare unei functi...",""],
["./aplicatii.htm","Aplicatii","﻿Aplicatii Top Previous Next Aplicatia HR Executive permite configurarea mai multor aplicatii. O aplicatie poate fi un program informatic al compa...",""],
["./aplicatii2.htm","Aplicatii","﻿Aplicatii Top Previous Next Pentru adaugarea unei noi aplicatii se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul ...",""],
["./autentificarea_in_aplicatie.htm","Autentificarea","﻿Autentificarea Top Previous Next Prima fereastra pe care o vede un utilizator care doreste sa foloseasca aplicatia HR Executive este fereastra de...",""],
["./campuri_custom.htm","Campuri custom","﻿Campuri custom Top Previous Next Aplicatia informatica HR Executive permite, pe langa informatiile generale, si introducerea unor informatii conf...",""],
["./capitolul_1_actiuni_divizii.htm","Actiuni divizii","﻿Actiuni divizii Top Previous Next Capitol [Actiuni divizii] prezinta functionalitatile disponibile in modulul Performanta in fereatra [Actiuni di...",""],
["./capitolul_2_plan_actiuni.htm","Plan actiuni","﻿Plan actiuni Top Previous Next Acest capitol prezinta fereastra [Plan actiunii]: • Plan actiuni • Actiune noua • Modifica actiune • Istoric actiu...",""],
["./capitolul_2_plan_actiuni2.htm","Plan actiuni","﻿Plan actiuni Top Previous Next Modul Performanta &#62; Plan actiuni Fereastra de [Plan Actiuni] contine lista de actiuni definite de managerul care e...",""],
["./centre_de_cost.htm","Centre de cost","﻿Centre de cost Top Previous Next Aplicatia HR Executive permite configurarea centrelor de cost ale companiei dumneavoastra. ",""],
["./centre_de_cost2.htm","Centre de cost","﻿Centre de cost Top Previous Next Pentru adaugarea unui nou centru de cost se urmeaza pasii: • din meniul principal se alege [Administrare] • din ...",""],
["./companii.htm","Companii","﻿Companii Top Previous Next Pentru a putea vizualiza companiile adaugate in aplicatia HR Executive, se alege din meniul principal optiunea [Compan...",""],
["./companii2.htm","Companii","﻿Companii Top Previous Next Modulul de gestionare a companiilor care colaboreaza sau au colaborat, sau au fost inregistrate de catre personalul co...",""],
["./companii_training.htm","Companii training","﻿Companii training Top Previous Next Pentru a putea vizualiza o lista a companiilor de training adaugate in aplicatia HR Executive, se alege din m...",""],
["./cv.htm","Fereastra CV","﻿Fereastra CV Top Previous Next Campurile introduse anterior necesare pentru completarea unui CV sunt preluate automat. Aceste campuri sunt: Nume ...",""],
["./date_autentificare.htm","Fereastra Date autentificare","﻿Fereastra Date autentificare Top Previous Next In aceastra fereastra de [Date autentificare] se poate seta utilizatorul si parola pentru accesul ...",""],
["./departament.htm","Departamente","﻿Departamente Top Previous Next Aplicatia HR Executive permite configurarea departamentelor existente in cadrul companiei dumneavoastra, dar nu nu...",""],
["./departament2.htm","Departament","﻿Departament Top Previous Next Pentru adaugarea unui nou departament se urmeaza pasii: • din meniul principal se alege [Administrare] • din submen...",""],
["./despre.htm","Despre","﻿Despre HR Executive 2.0 Top Previous HR Executive Version 2.0 Informatii despre numerotarea versiuniilor aplicatiei HR Executive Aplicatia HR Exe...",""],
["./dimensiune.htm","Dimensiune","﻿Dimensiune Top Previous Next Modul Performanta &#62; Dimensiune Fereastra [Dimensiune] este compusa dintr-o lista de dimensiuni. Pentru a adauga o no...",""],
["./domenii.htm","Domenii","﻿Domenii Top Previous Next Aplicatia HR Executive permite configurarea de domeniilor de activitate pe care compania dumneavoastra le intalneste sa...",""],
["./domenii2.htm","Domenii","﻿Domenii Top Previous Next Pentru adaugarea unui nou domeniu se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Adm...",""],
["./evenimente.htm","Evenimente","﻿Evenimente Top Previous Next Fereastra evenimente contine lista completa a evenimentelor introduse in aplicatie. Prin evenimente se poate inteleg...",""],
["./fereastra_acces_performanta.htm","Fereastra Acces Performanta","﻿Fereastra Acces Performanta Top Previous Next In fereastra [Acces Performanta] se pot seta pentru persoana drepturile de acces in HR Executive - ...",""],
["./fereastra_concediu.htm","Fereastra Concediu","﻿Fereastra Concediu Top Previous Next Ferastra [Concediu de odihna] contine urmatoarele campuri: Concediu de odihna (setare numar de zile de conce...",""],
["./fereastra_date_profesionale.htm","Fereastra Date profesionale","﻿Fereastra Date profesionale Top Previous Next Fereastra [Date profesionale] • Profesia: (camp obligatoriu de completat) • Pregatire:(camp obligat...",""],
["./fereastra_incadrare.htm","Fereastra Incadrare","﻿Fereastra Incadrare Top Previous Next Ferastra [Incadrare] contine urmatoarele campuri: • Centru cost: centru de cost la care este asociata perso...",""],
["./fereastra_masini.htm","Fereastra Masini","﻿Fereastra Masini Top Previous Next In aceastra fereastra [Masini] se poate specifica daca persoana are masina primita de la companie. Se pot comp...",""],
["./fereastra_payroll.htm","Fereastra Payroll","﻿Fereastra Payroll Top Previous Next Ferastra [Payroll] contine urmatoarele campuri: • Data angajarii: (camp obligatoriu) - data la care persoana ...",""],
["./functie.htm","Functie","﻿Functie Top Previous Next Pentru adaugarea unei noi functii se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Adm...",""],
["./functii.htm","Functii","﻿Functii Top Previous Next Aplicatia HR Executive permite configurarea tuturor functiilor pe care compania dumneavoastra le foloseste. ",""],
["./help.htm","Help","﻿Help Top Previous Next Help Pentru a putea gasi informatia dorita despre functionalitatile aplicateiei HR Executive se pot folosi urmatoarele: In...",""],
["./home.htm","Home","﻿Home Top Previous Next Fereastra [Home] (sau Pagina de start) contine stiri si informatii de profil, utile pentru persoanele care folosesc aplica...",""],
["./informatii_generale.htm","Informatii generale","﻿Informatii generale Top Previous Next Pentru a putea vedea oricand cine este autentificat, aplicatia HR Executive va afiseaza in partea stanga, i...",""],
["./introduction.htm","Introducere","﻿Introducere Top Next Bine ati venit! HR Executive este o aplicatie informatica care are ca scop usurarea gestionarii activitatilor dintr-un depar...",""],
["./istoric_actiuni.htm","Istoric actiuni","﻿Istoric actiuni Top Previous Next Modul Performanta &#62; Plan actiuni Fereastra [Istoric actiuni] poate fi aceesata din fereastra [Plan actiuni] pri...",""],
["./joburi.htm","Joburi","﻿Joburi Top Previous Next Pentru a putea vizualiza joburile adaugate in aplicatia HR Executive, se alege din meniul principal optiunea [Joburi]. A...",""],
["./joburi2.htm","Joburi","﻿Joburi Top Previous Next Modulul de gestionare a joburilor. Aici se pot vedea joburile vacante in cadrul companiei sau chiar joburi vacante ident...",""],
["./lista_actiuni_divizii.htm","Lista actiuni divizii","﻿Lista actiuni divizii Top Previous Next Modul Performanta &#62; Actiuni divizii Fereastra [Actiuni divizii] este compusa dintr-o zona de filtrare si ...",""],
["./lista_evenimente.htm","Lista evenimente","﻿Lista evenimente Top Previous Next Pentru a putea vizualiza evenimentele adaugate in aplicatia HR Executive, se alege din meniul principal optiun...",""],
["./lista_obiective_angajati.htm","Lista angajati Obiective","﻿Lista angajati obiective Top Previous Next Modul Performanta &#62; Obiective angajati Ca in orice alta fereastra de afisare din aplicatia HR Executiv...",""],
["./lista_personalizata.htm","Lista personalizata","﻿Lista personalizata Top Previous Next Acest modul se poate folosi pentru a adauga coloane aditionale in listele Personal, Companii si Joburi. Pen...",""],
["./lista_traininguri.htm","Lista traininguri","﻿Lista traininguri Top Previous Next Pentru a putea vizualiza trainingurile adaugate in aplicatia HR Executive, se alege din meniul principal opti...",""],
["./locatii.htm","Locatie","﻿Locatie Top Previous Next Pentru adaugarea unei noi locatii se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Adm...",""],
["./locatii_si_sali.htm","Locatii si sali","﻿Locatii si sali Top Previous Next Aplicatia HR Executive permite configurarea mai multor locatii si sali. O locatie poate fi sediul central al co...",""],
["./modifica_actiune.htm","Modifica actiune","﻿Modifica actiune Top Previous Next Modul Performanta &#62; Plan actiuni Fereastra [Modifica actiune] contine urmatoarele elemente: Campurile: • Anul ...",""],
["./module.htm","Module","﻿Module Top Previous Next Pentru adaugarea unui nou modul se urmeaza pasii: • din meniul principal se alege [Administrare] • din submeniul [Admini...",""],
["./modul_it.htm","Fereastra Modul IT","﻿Fereastra Modul IT Top Previous Next Ferastra [Modul IT], folosita pentru a specifica drepturile in aplicatiile companiei pentru fiecare angajat,...",""],
["./obiective_angajati.htm","Obiective angajati","﻿Obiective angajati Top Previous Next Acest capitol prezinta fereastra [Obiective angajati]: • Lista angajati obiective • Obiectiv nou ",""],
["./obiectiv_nou.htm","Obiectiv nou","﻿Obiectiv nou Top Previous Next Modul Performanta &#62; Obiective angajati In aceasta fereastra este deschis modulul [Date identificare], utilizatorul...",""],
["./performanta.htm","Modulul Performanta","﻿Modulul Performanta Top Previous Next Modulul de performanta are ca scop gestionarea actiunilor definite de catre fiecare manager de departament. ",""],
["./personal.htm","Personal","﻿Personal Top Previous Next Meniul [Personal] este folosit pentru a putea vedea lista completa a angajatilor actuali sau angajati care au parasit ...",""],
["./personalsubmeniu.htm","Personal","﻿Personal Top Previous Next Pentru a putea vizualiza personele adaugate in aplicatia HR Executive, se alege din meniul principal [Personal], urman...",""],
["./profesii.htm","Profesii","﻿Profesii Top Previous Next Aplicatia HR Executive permite configurarea profesiilor pe care compania dumneavoastra le intalneste, sau le foloseste...",""],
["./rapoarte.htm","Rapoarte","﻿Rapoarte Top Previous Next Aplicatia informatica HR Executive poate genera diferite tipuri de rapoarte. Pentru a putea acesa/rula rapoartele se f...",""],
["./rapoarte2.htm","Rapoarte","﻿Rapoarte Top Previous Next Pentru setarea unui nou raport managerial se urmeaza pasii: • din meniul principal se alege [Administrare] • din subme...",""],
["./salii.htm","Sala","﻿Sali Top Previous Next Pentru adaugarea unei noi sali se urmeaza pasii: • din meniul principal se apasa [Administrare] • din submeniul [Administr...",""],
["./schimbarea_parolei.htm","Schimbarea parolei","﻿Schimbarea parolei Top Previous Next Daca un utilizator doreste sa isi schimbe parola setata de administratorul aplicatiei, trebuie sa urmeze urm...",""],
["./setare_drepturi.htm","Setare drepturi","﻿Setare drepturi Top Previous Next Pentru setarea drepturilor de acces ale unui utilizator nou se urmeaza pasii: • din meniul principal se apasa [...",""],
["./setare_parola.htm","Setare parola","﻿Setare parola Top Previous Next Pentru a putea seta o noua parola pentru un utilizator se urmeaza pasii: • din meniul principal se alege [Adminis...",""],
["./setari.htm","Setari","﻿Setari Top Previous Next Afisarea listei personalizate, pe trei mari categorii – Personal, Companii, Joburi. Bifeaza si salveaza ceea ce te avant...",""],
["./setari_speciale.htm","Setari speciale","﻿Setari speciale Top Previous Next Pentru setarea drepturilor speciale ale unui utilizator se urmeaza pasii: • din meniul principal se alege [Admi...",""],
["./sterge_utilizator.htm","Stergere utilizator","﻿Stergere utilizator Top Previous Next Pentru a sterge un utilizator se urmeaza pasii: • din meniul principal se alege [Administrare] • din submen...",""],
["./tipuri_de_training.htm","Tipuri de training","﻿Tipuri de training Top Previous Next Pentru adaugarea unui nou tip de training se urmeaza pasii: • din meniul principal se alege [Training] • din...",""],
["./training.htm","Training","﻿Training Top Previous Next Meniul Training centralizeaza informatii despre traingurile desfasurate, planificate, sau programate si le grupeaza in...",""],
["./utilizatori.htm","Utilizatori","﻿Utilizatori Top Previous Next Pentru a putea folosi aplicatia HR Executive fiecare utilizator are nevoie de un utilizator si o parola. Administra...",""],
["./welcome_topic.htm","Bine ati venit","﻿Bine ati venit Top Previous Next Aplicatia informatica, HR Executive, pentru gestionarea activitatilor dintr-un departament de resurse umane a fo...",""]];
