titles = new Array("Adauga persoana",
	"Utilizator",
	"Adauga companie",
	"Adauga eveniment",
	"Adauga job",
	"Profesie",
	"Adauga training",
	"Administrare",
	"Aplicatii",
	"Aplicatii",
	"Autentificarea",
	"Campuri custom",
	"Centre de cost",
	"Centre de cost",
	"Companii",
	"Companii",
	"Companii training",
	"Fereastra CV",
	"Departamente",
	"Departament",
	"Despre",
	"Domenii",
	"Domenii",
	"Evenimente",
	"Fereastra Concediu",
	"Fereastra Date profesionale",
	"Fereastra Masini",
	"Fereastra Payroll",
	"Functie",
	"Functii",
	"Help",
	"Home",
	"Informatii generale",
	"Introducere",
	"Joburi",
	"Joburi",
	"Lista evenimente",
	"Lista personalizata",
	"Lista traininguri",
	"Locatie",
	"Locatii si sali",
	"Module",
	"Fereastra Modul IT",
	"Personal",
	"Personal",
	"Profesii",
	"Rapoarte",
	"Rapoarte",
	"Sala",
	"Schimbarea parolei",
	"Setare drepturi",
	"Setare parola",
	"Setari",
	"Setari speciale",
	"Stergere utilizator",
	"Tipuri de training",
	"Training",
	"Utilizatori",
	"Bine ati venit");